name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
  build-linux:
    strategy:
      matrix:
        image:
          - swift:5.3-focal
          - swift:5.4-focal
          - swift:5.5-focal
          - swift:5.6-focal
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v

